### PR TITLE
Technic plus compatibility full

### PR DESCRIPTION
**Pull request by S-S-X**
Full compatibility with Technic Plus v2.x tool registration API.

Another option: #19 minimal compatibility which wont fix deprecation warnings.

See https://github.com/mt-mods/technic/pull/233

### CODE REVIEW

**Comment by OgelGames** [comment]
~~The new version is missing the `on_refill` callback, which means it can't be charged in `unified_inventory`'s refill slot.~~

**Comment by S-S-X** [comment]
> The new version is missing the `on_refill` callback, which means it can't be charged in `unified_inventory`'s refill slot.

Unified inventory refill is fully supported (read the code in technic repo or test)

**Comment by OgelGames** [comment]
> Unified inventory refill is fully supported (read the code in technic repo or test)

I just realized that... :facepalm:

**Comment by berengma** [comment]
I had to look what that technic_plus is. 
So as far as I understand it is a technic fork and your PR is only adding the tools for it.
Which means tools for technic keep untouched.
I'll check that asap.

**Comment by S-S-X** [comment]
> I had to look what that technic_plus is. So as far as I understand it is a technic fork and your PR is only adding the tools for it. Which means tools for technic keep untouched. I'll check that asap.

Technic Plus has completely different mechanism for running networks, list of significant things that have changed would be too big here but ContentDB and release notes has some info.
https://content.minetest.net/packages/mt-mods/technic_plus/
https://github.com/mt-mods/technic/releases

**Comment by berengma** [comment]
looked ok, merged.

**Pull request merged**
