### PR TITLE
Technic plus compatibility minimal

### PR DESCRIPTION
**Pull request by S-S-X**
Minimal compatibility with Technic Plus v2.x tool registration API.

Another option: #18 full compatibility which will fix deprecation warnings.

See https://github.com/mt-mods/technic/pull/233

### CODE REVIEW

**Comment by OgelGames** [comment]
This doesn't change how the charge is saved, so the tools will have infinite charge when technic plus is used.

**Comment by S-S-X** [comment]
> This doesn't change how the charge is saved, so the tools will have infinite charge when technic plus is used.

This does change how the charge is saved, read the code or test first.
edit. It does still leave old charge data but that data is irrelevant with Technic Plus, that's why this is called "minimal".
Minimal does not mean that support is worse but it leaves unnecessary metadata serializations / writing, all functionality is still there.

**Comment by OgelGames** [comment]
`technic.set_RE_wear` doesn't exist in the new API: https://github.com/berengma/farming_nextgen/blob/7c23a3a79656cd129224878917c3ebedc3d37b7c/harvester.lua#L238-L239

**Comment by S-S-X** [comment]
> technic.set_RE_wear doesn't exist in the new API:
> https://github.com/berengma/farming_nextgen/blob/7c23a3a79656cd129224878917c3ebedc3d37b7c/harvester.lua#L238-L239

Good find, actual compatibility shim can be found from compat/tools.lua
edit. To be clear: yes it does exist and yes this does work. Test if you're unsure.

**Comment by berengma** [comment]
merged the other PR, can be closed.

**Pull request closed without merging**
